name: nicwir-tau
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=19.3.1=py37_0
  - python=3.7.6
  - cycler==0.10.0
  - imageio==2.9.0
  - kiwisolver==1.3.2
  - matplotlib==3.4.3
  - numpy==1.21.2
  - Pillow==8.3.2
  - pyparsing==2.4.7
  - python-dateutil==2.8.2
  - six==1.16.0
  - torch==1.9.0
  - torchvision==0.10.0
  - tqdm==4.62.2
  - typing-extensions==3.10.0.2
